language: php

php:
  - 7.4

git:
  quiet: true

jobs:
  include:
    - name: "Unit Test"
      env: UNIT_TEST=true
    - name: "Static Analysis"
      env: STATIC_ANALYSIS=true
    - name: "Code Coverage"
      env: CODE_COVERAGE=true
    - name: "Code Style"
      env: CODE_STYLE=true

before_script:
  - if [[ $CODE_COVERAGE != true ]]; then phpenv config-rm xdebug.ini; fi
  - |
    if [[ $CODE_STYLE == true ]]; then
      composer global require friendsofphp/php-cs-fixer
      export PATH="$PATH:$HOME/.composer/vendor/bin"
    fi
  - composer install --prefer-dist --quiet --no-interaction

script:
  - if [[ $UNIT_TEST == true ]]; then vendor/bin/phpunit; fi
  - if [[ $STATIC_ANALYSIS == true ]]; then vendor/bin/phpstan analyse; fi
  - if [[ $CODE_STYLE == true ]]; then php-cs-fixer --diff --dry-run --verbose fix .; fi

after_success:
  - |
    if [[ $CODE_COVERAGE == true && $TRAVIS_BRANCH == "master" ]]; then
      vendor/bin/phpunit --coverage-clover build/logs/clover.xml
      wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
      php php-coveralls.phar --verbose
    fi
